"""Generate docs/metrics/backtest.json and docs/METRICS.md from real runs (never hand-typed).

    python -m scripts.metrics
"""
from __future__ import annotations

import json
from datetime import date
from pathlib import Path

import scripts  # noqa: F401
from app.config import SOURCE_DB
from app.db.conn import connect_readonly
from app.forecast.backtest import run
from app.forecast.panel import build_panel
from app.services.data import load_events

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "metrics"


def main() -> int:
    panel = build_panel(load_events(connect_readonly(SOURCE_DB)))
    r = run(panel, date(2025, 10, 1), date(2026, 4, 1), [date(2026, 6, 1), date(2026, 6, 15), date(2026, 7, 1)], 60,
            date(2026, 8, 30), use_lightgbm=True)
    r["interval"].pop("aci_trace", None)
    r["protocol"] = {"train_origins": "weekly 2025-10-01 → 2026-04-01 (targets < 2026-06-01)",
                     "test_origins": ["2026-06-01", "2026-06-15", "2026-07-01"], "horizon_days": 60,
                     "data": "DynamicPricing/data/APS-02.db (read-only)"}
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "backtest.json").write_text(json.dumps(r, indent=2, default=float), encoding="utf-8")
    ev = json.loads((OUT / "ai_evals.json").read_text(encoding="utf-8")) if (OUT / "ai_evals.json").exists() else None
    p, n = r["pickup"], r["naive"]
    lines = [
        "# Metrics (generated by `python -m scripts.metrics` — do not edit by hand)", "",
        "## Forecast backtest (rolling origin, held-out June–July 2026, production code)", "",
        "| Measure | Pickup (champion P50) | Trailing-rate naive | Improvement |", "|---|---|---|---|",
        f"| City × day MAE | {p['city_day_mae']:.4f} | {n['city_day_mae']:.4f} | {r['improvement_vs_naive']['city_day_mae']:.1%} |",
        f"| City × day Poisson deviance | {p['city_day_poisson_deviance']:.4f} | {n['city_day_poisson_deviance']:.4f} | "
        f"{r['improvement_vs_naive']['city_day_poisson_deviance']:.1%} |",
        f"| National × week accuracy (1 − WAPE) | {p['national_week_accuracy']:.1%} | {n['national_week_accuracy']:.1%} | |",
        f"| National × day accuracy (1 − WAPE) | {p['national_day_accuracy']:.1%} | {n['national_day_accuracy']:.1%} | |",
        "", f"Rate window chosen by nested validation: {r['window_days']} days. Cells scored: {p['cells']}.", "",
        "## Uncertainty band (P10–P90, 7-day signal)", "", "| Method | Coverage (target 80%) | Interval score |", "|---|---|---|",
    ]
    for k, v in r["interval"].items():
        lines.append(f"| {k} | {v['coverage']:.1%} | {v['interval_score']:.3f} |")
    lines += ["", "The live system re-runs this selection on its own recent history at every fit (dp_model_selection).", ""]
    if ev:
        w, e = ev["whatif"], ev["events"]
        lines += ["## AI evals (" + ev["mode"] + ")", "",
                  f"- A4 what-if parser: {w['valid_parsed']}/{w['valid_total']} prompts parsed to the intended config "
                  f"(target ≥ 18/20); {w['malformed_rejected']}/{w['malformed_total']} malformed prompts rejected (target 100%).",
                  f"- A3 event extractor: micro-precision {e['micro_precision']:.0%} on {e['rows']} hand-labelled rows "
                  "(target ≥ 80%). Offline, the stated rules were written by the same team that labelled the rows, so "
                  "this offline score is NOT independent evidence; the live-LLM run is the meaningful measurement.",
                  "- A2 narrator: the numeric gate is a hard block; `/v1/metrics` reports the live pass rate "
                  "(narration_gate).", ""]
    (ROOT / "docs" / "METRICS.md").write_text("\n".join(lines), encoding="utf-8")
    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
