// Captures the key screens of the running app (python -m uvicorn ... on :8000). Usage: node e2e/screenshots.mjs <out-dir>
import { chromium } from "@playwright/test";
import fs from "fs";
const OUT = process.argv[2];
const TOKEN = fs.readFileSync("../.env", "utf8").match(/^ADMIN_TOKEN=(.+)$/m)[1].trim();
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [];
page.on("console", (m) => { if (m.type() === "error") errors.push(m.text()); });
page.on("pageerror", (e) => errors.push(String(e)));
await page.goto("http://127.0.0.1:8000/");
await page.waitForSelector("select");
await page.waitForTimeout(600);
await page.screenshot({ path: `${OUT}/01-search.png` });
await page.getByRole("button", { name: /कमरे देखें|Show rooms|ಕೊಠಡಿಗಳನ್ನು/ }).click();
await page.waitForSelector("li.card");
await page.waitForTimeout(500);
await page.screenshot({ path: `${OUT}/02-results.png`, fullPage: true });
await page.locator("li.card a").first().click();
await page.waitForSelector("article");
await page.waitForTimeout(800);
await page.screenshot({ path: `${OUT}/03-pass-hi.png`, fullPage: true });
await page.getByRole("button", { name: "ಕನ್ನಡ" }).click();
await page.waitForTimeout(1200);
await page.screenshot({ path: `${OUT}/04-pass-kn.png`, fullPage: true });
await page.goto("http://127.0.0.1:8000/desk");
await page.fill("input[type=password]", TOKEN);
await page.getByRole("button", { name: /Sign in/ }).click();
await page.waitForSelector("svg[role=img]");
await page.waitForTimeout(1200);
await page.screenshot({ path: `${OUT}/05-desk-curve.png`, fullPage: true });
const box = await page.locator("svg[role=img]").first().boundingBox();
await page.mouse.click(box.x + box.width * 0.55, box.y + box.height * 0.5);
await page.waitForSelector("[role=dialog]");
await page.waitForTimeout(1200);
await page.screenshot({ path: `${OUT}/06-drawer.png` });
console.log("errors:", JSON.stringify(errors.slice(0, 10)));
await browser.close();
